#!/bin/bash

CURRENT_DIR=$(pwd) # Get the current directory
SEARCHED_DIR_ARG=$@ # used if there are multiple arguments
ARG_TOTAL=$# # used for condition for number of arguments logic

function clear_and_current_dir() {
    clear -x;
    echo "Current Directory: ${CURRENT_DIR}"; 
}

function clsla_no_arg() {
    if [ "${1}" != "" ]
    then
        echo "Searched Directory: ${1}"
    fi;
    echo ""
    no_arg_list_files
}

function no_arg_list_files() {
    if [ "${1}" = "" ]
        then
            # ls -F ${1} --color=auto
            ls -lhtFa ${1} --color=auto
        else
            # ls -F "${1}" --color=auto
            ls -lhtFa "${1}" --color=auto
    fi
}

function searched_file() {
    for ARG in ${SEARCHED_DIR_ARG}
    do
        if [ "${ARG}" != "" ]
        then
           if [ -d ${ARG} ] 
           then    
                echo "Searched Directory: ${ARG}"
            elif [ -f ${ARG} ]
            then
                echo "Searched file: ${ARG}"
            fi
        fi
    done
    echo ""
    list_file
}

function list_file() {
    for ARG in ${SEARCHED_DIR_ARG}
    do
        if [ "${ARG}" = "" ]
        then
            # ls -F ${ARG} --color=auto 
            ls -lhtFa ${ARG} --color=auto 
            echo ""  
        else
            # ls -F "${ARG}" --color=auto
            ls -lhtFa "${ARG}" --color=auto
            echo ""
        fi
    done    
}

# Get Searched Directory
if [ ${ARG_TOTAL} = 0 ]
then
    clear_and_current_dir
    clsla_no_arg
else
    # echo "${ARG_TOTAL}";
    clear_and_current_dir
    searched_file
fi

